name: qudi-hira-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.1
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asteval=0.9.27
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.10.3
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.1.0
  - colorama=0.4.5
  - cryptography=37.0.4
  - cycler=0.11.0
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - flit-core=3.7.1
  - fonttools=4.34.4
  - freetype=2.10.4
  - future=0.18.2
  - giflib=5.2.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.8.0
  - ipykernel=6.15.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.7.1
  - jupyter_client=7.3.4
  - jupyter_core=4.10.0
  - jupyter_server=1.18.1
  - jupyterlab=3.4.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.15.0
  - kiwisolver=1.4.3
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lmfit=1.0.3
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.3.7
  - nbclient=0.6.6
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.12
  - notebook-shim=0.1.0
  - numpy=1.23.1
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.12.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.10.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.10
  - pytz=2022.1
  - pyzmq=23.2.0
  - readline=8.1.2
  - requests=2.28.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=63.1.0
  - setuptools-scm=7.0.5
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.39.0
  - stack_data=0.3.0
  - terminado=0.15.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.64.0
  - traitlets=5.3.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022a
  - uncertainties=3.1.7
  - unicodedata2=14.0.0
  - urllib3=1.26.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.3
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
